// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grnilhcmwnrqxrfgnxps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybmlsaGNtd25ycXhyZmdueHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNDY3NTQsImV4cCI6MjA1NjYyMjc1NH0.g3SIL43aBStuA0KRonJNFLmLKFs1jcKTjEVa7oABPcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);